//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TravelWebSite.PaqueteWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaquetesPopularesWSSoapBinding", Namespace="TravelAdmin")]
    public partial class PaquetesPopularesWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OBTENERPREGUNTASOperationCompleted;
        
        private System.Threading.SendOrPostCallback SLIDEROperationCompleted;
        
        private System.Threading.SendOrPostCallback CATALOGOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback HEADERPUBLICIDADOperationCompleted;
        
        private System.Threading.SendOrPostCallback HEADERTELEFONOOperationCompleted;
        
        private System.Threading.SendOrPostCallback GUARDARPREGUNTASOperationCompleted;
        
        private System.Threading.SendOrPostCallback RECUPERARPREGUNTASROperationCompleted;
        
        private System.Threading.SendOrPostCallback RECUPERARVALUEPREGUNTASROperationCompleted;
        
        private System.Threading.SendOrPostCallback ACTUALIZARPASSWORDOperationCompleted;
        
        private System.Threading.SendOrPostCallback TEOFRECEMOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback VERIFICARUSUARIOREDESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETINFORMACIONADICIONALOperationCompleted;
        
        private System.Threading.SendOrPostCallback BUSQUEDAPAQUETESOperationCompleted;
        
        private System.Threading.SendOrPostCallback SELECCIONARPAGINACONTENIDOOperationCompleted;
        
        private System.Threading.SendOrPostCallback OBTENERNOMBREAPELLIDOOperationCompleted;
        
        private System.Threading.SendOrPostCallback PAGINACONTENIDOOperationCompleted;
        
        private System.Threading.SendOrPostCallback PAQUETESOperationCompleted;
        
        private System.Threading.SendOrPostCallback BOLETINFOOTEROperationCompleted;
        
        private System.Threading.SendOrPostCallback DESTINOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback DESTINODETALLEOperationCompleted;
        
        private System.Threading.SendOrPostCallback COTIZARPAQUETEOperationCompleted;
        
        private System.Threading.SendOrPostCallback COORDENADASPAQUETEOperationCompleted;
        
        private System.Threading.SendOrPostCallback CONTACTOALMACENAROperationCompleted;
        
        private System.Threading.SendOrPostCallback CONTACTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback CATEGORIASBUSQUEDAOperationCompleted;
        
        private System.Threading.SendOrPostCallback REGISTROUSUARIOOperationCompleted;
        
        private System.Threading.SendOrPostCallback INICIARSESIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback INFORMACIONADICIONALOperationCompleted;
        
        private System.Threading.SendOrPostCallback RECOMENDADOSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaquetesPopularesWS() {
            this.Url = global::TravelWebSite.Properties.Settings.Default.TravelWebSite_PaqueteWS_PaquetesPopularesWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OBTENERPREGUNTASCompletedEventHandler OBTENERPREGUNTASCompleted;
        
        /// <remarks/>
        public event SLIDERCompletedEventHandler SLIDERCompleted;
        
        /// <remarks/>
        public event CATALOGOSCompletedEventHandler CATALOGOSCompleted;
        
        /// <remarks/>
        public event HEADERPUBLICIDADCompletedEventHandler HEADERPUBLICIDADCompleted;
        
        /// <remarks/>
        public event HEADERTELEFONOCompletedEventHandler HEADERTELEFONOCompleted;
        
        /// <remarks/>
        public event GUARDARPREGUNTASCompletedEventHandler GUARDARPREGUNTASCompleted;
        
        /// <remarks/>
        public event RECUPERARPREGUNTASRCompletedEventHandler RECUPERARPREGUNTASRCompleted;
        
        /// <remarks/>
        public event RECUPERARVALUEPREGUNTASRCompletedEventHandler RECUPERARVALUEPREGUNTASRCompleted;
        
        /// <remarks/>
        public event ACTUALIZARPASSWORDCompletedEventHandler ACTUALIZARPASSWORDCompleted;
        
        /// <remarks/>
        public event TEOFRECEMOSCompletedEventHandler TEOFRECEMOSCompleted;
        
        /// <remarks/>
        public event VERIFICARUSUARIOREDESCompletedEventHandler VERIFICARUSUARIOREDESCompleted;
        
        /// <remarks/>
        public event GETINFORMACIONADICIONALCompletedEventHandler GETINFORMACIONADICIONALCompleted;
        
        /// <remarks/>
        public event BUSQUEDAPAQUETESCompletedEventHandler BUSQUEDAPAQUETESCompleted;
        
        /// <remarks/>
        public event SELECCIONARPAGINACONTENIDOCompletedEventHandler SELECCIONARPAGINACONTENIDOCompleted;
        
        /// <remarks/>
        public event OBTENERNOMBREAPELLIDOCompletedEventHandler OBTENERNOMBREAPELLIDOCompleted;
        
        /// <remarks/>
        public event PAGINACONTENIDOCompletedEventHandler PAGINACONTENIDOCompleted;
        
        /// <remarks/>
        public event PAQUETESCompletedEventHandler PAQUETESCompleted;
        
        /// <remarks/>
        public event BOLETINFOOTERCompletedEventHandler BOLETINFOOTERCompleted;
        
        /// <remarks/>
        public event DESTINOSCompletedEventHandler DESTINOSCompleted;
        
        /// <remarks/>
        public event DESTINODETALLECompletedEventHandler DESTINODETALLECompleted;
        
        /// <remarks/>
        public event COTIZARPAQUETECompletedEventHandler COTIZARPAQUETECompleted;
        
        /// <remarks/>
        public event COORDENADASPAQUETECompletedEventHandler COORDENADASPAQUETECompleted;
        
        /// <remarks/>
        public event CONTACTOALMACENARCompletedEventHandler CONTACTOALMACENARCompleted;
        
        /// <remarks/>
        public event CONTACTOCompletedEventHandler CONTACTOCompleted;
        
        /// <remarks/>
        public event CATEGORIASBUSQUEDACompletedEventHandler CATEGORIASBUSQUEDACompleted;
        
        /// <remarks/>
        public event REGISTROUSUARIOCompletedEventHandler REGISTROUSUARIOCompleted;
        
        /// <remarks/>
        public event INICIARSESIONCompletedEventHandler INICIARSESIONCompleted;
        
        /// <remarks/>
        public event INFORMACIONADICIONALCompletedEventHandler INFORMACIONADICIONALCompleted;
        
        /// <remarks/>
        public event RECOMENDADOSCompletedEventHandler RECOMENDADOSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.OBTENERPREGUNTAS", RequestElementName="PaquetesPopularesWS.OBTENERPREGUNTAS", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.OBTENERPREGUNTASResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Tramapreguntas")]
        public string OBTENERPREGUNTAS() {
            object[] results = this.Invoke("OBTENERPREGUNTAS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OBTENERPREGUNTASAsync() {
            this.OBTENERPREGUNTASAsync(null);
        }
        
        /// <remarks/>
        public void OBTENERPREGUNTASAsync(object userState) {
            if ((this.OBTENERPREGUNTASOperationCompleted == null)) {
                this.OBTENERPREGUNTASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOBTENERPREGUNTASOperationCompleted);
            }
            this.InvokeAsync("OBTENERPREGUNTAS", new object[0], this.OBTENERPREGUNTASOperationCompleted, userState);
        }
        
        private void OnOBTENERPREGUNTASOperationCompleted(object arg) {
            if ((this.OBTENERPREGUNTASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OBTENERPREGUNTASCompleted(this, new OBTENERPREGUNTASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.SLIDER", RequestElementName="PaquetesPopularesWS.SLIDER", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.SLIDERResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Slider")]
        public string SLIDER() {
            object[] results = this.Invoke("SLIDER", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SLIDERAsync() {
            this.SLIDERAsync(null);
        }
        
        /// <remarks/>
        public void SLIDERAsync(object userState) {
            if ((this.SLIDEROperationCompleted == null)) {
                this.SLIDEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSLIDEROperationCompleted);
            }
            this.InvokeAsync("SLIDER", new object[0], this.SLIDEROperationCompleted, userState);
        }
        
        private void OnSLIDEROperationCompleted(object arg) {
            if ((this.SLIDERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SLIDERCompleted(this, new SLIDERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.CATALOGOS", RequestElementName="PaquetesPopularesWS.CATALOGOS", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.CATALOGOSResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paginacontenidohtml")]
        public string CATALOGOS() {
            object[] results = this.Invoke("CATALOGOS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CATALOGOSAsync() {
            this.CATALOGOSAsync(null);
        }
        
        /// <remarks/>
        public void CATALOGOSAsync(object userState) {
            if ((this.CATALOGOSOperationCompleted == null)) {
                this.CATALOGOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCATALOGOSOperationCompleted);
            }
            this.InvokeAsync("CATALOGOS", new object[0], this.CATALOGOSOperationCompleted, userState);
        }
        
        private void OnCATALOGOSOperationCompleted(object arg) {
            if ((this.CATALOGOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CATALOGOSCompleted(this, new CATALOGOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.HEADERPUBLICIDAD", RequestElementName="PaquetesPopularesWS.HEADERPUBLICIDAD", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.HEADERPUBLICIDADResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paginacontenidohtml")]
        public string HEADERPUBLICIDAD() {
            object[] results = this.Invoke("HEADERPUBLICIDAD", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HEADERPUBLICIDADAsync() {
            this.HEADERPUBLICIDADAsync(null);
        }
        
        /// <remarks/>
        public void HEADERPUBLICIDADAsync(object userState) {
            if ((this.HEADERPUBLICIDADOperationCompleted == null)) {
                this.HEADERPUBLICIDADOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHEADERPUBLICIDADOperationCompleted);
            }
            this.InvokeAsync("HEADERPUBLICIDAD", new object[0], this.HEADERPUBLICIDADOperationCompleted, userState);
        }
        
        private void OnHEADERPUBLICIDADOperationCompleted(object arg) {
            if ((this.HEADERPUBLICIDADCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HEADERPUBLICIDADCompleted(this, new HEADERPUBLICIDADCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.HEADERTELEFONO", RequestElementName="PaquetesPopularesWS.HEADERTELEFONO", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.HEADERTELEFONOResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paginacontenidohtml")]
        public string HEADERTELEFONO() {
            object[] results = this.Invoke("HEADERTELEFONO", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HEADERTELEFONOAsync() {
            this.HEADERTELEFONOAsync(null);
        }
        
        /// <remarks/>
        public void HEADERTELEFONOAsync(object userState) {
            if ((this.HEADERTELEFONOOperationCompleted == null)) {
                this.HEADERTELEFONOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHEADERTELEFONOOperationCompleted);
            }
            this.InvokeAsync("HEADERTELEFONO", new object[0], this.HEADERTELEFONOOperationCompleted, userState);
        }
        
        private void OnHEADERTELEFONOOperationCompleted(object arg) {
            if ((this.HEADERTELEFONOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HEADERTELEFONOCompleted(this, new HEADERTELEFONOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.GUARDARPREGUNTAS", RequestElementName="PaquetesPopularesWS.GUARDARPREGUNTAS", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.GUARDARPREGUNTASResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Valido")]
        public short GUARDARPREGUNTAS(string Usuarioemail, string Usuariopregunta1, string Usuariorespuesta1, string Usuariopregunta2, string Usuariorespuesta2) {
            object[] results = this.Invoke("GUARDARPREGUNTAS", new object[] {
                        Usuarioemail,
                        Usuariopregunta1,
                        Usuariorespuesta1,
                        Usuariopregunta2,
                        Usuariorespuesta2});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void GUARDARPREGUNTASAsync(string Usuarioemail, string Usuariopregunta1, string Usuariorespuesta1, string Usuariopregunta2, string Usuariorespuesta2) {
            this.GUARDARPREGUNTASAsync(Usuarioemail, Usuariopregunta1, Usuariorespuesta1, Usuariopregunta2, Usuariorespuesta2, null);
        }
        
        /// <remarks/>
        public void GUARDARPREGUNTASAsync(string Usuarioemail, string Usuariopregunta1, string Usuariorespuesta1, string Usuariopregunta2, string Usuariorespuesta2, object userState) {
            if ((this.GUARDARPREGUNTASOperationCompleted == null)) {
                this.GUARDARPREGUNTASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGUARDARPREGUNTASOperationCompleted);
            }
            this.InvokeAsync("GUARDARPREGUNTAS", new object[] {
                        Usuarioemail,
                        Usuariopregunta1,
                        Usuariorespuesta1,
                        Usuariopregunta2,
                        Usuariorespuesta2}, this.GUARDARPREGUNTASOperationCompleted, userState);
        }
        
        private void OnGUARDARPREGUNTASOperationCompleted(object arg) {
            if ((this.GUARDARPREGUNTASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GUARDARPREGUNTASCompleted(this, new GUARDARPREGUNTASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.RECUPERARPREGUNTASR", RequestElementName="PaquetesPopularesWS.RECUPERARPREGUNTASR", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.RECUPERARPREGUNTASRResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Tramarp")]
        public string RECUPERARPREGUNTASR(string Usuarioemail) {
            object[] results = this.Invoke("RECUPERARPREGUNTASR", new object[] {
                        Usuarioemail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RECUPERARPREGUNTASRAsync(string Usuarioemail) {
            this.RECUPERARPREGUNTASRAsync(Usuarioemail, null);
        }
        
        /// <remarks/>
        public void RECUPERARPREGUNTASRAsync(string Usuarioemail, object userState) {
            if ((this.RECUPERARPREGUNTASROperationCompleted == null)) {
                this.RECUPERARPREGUNTASROperationCompleted = new System.Threading.SendOrPostCallback(this.OnRECUPERARPREGUNTASROperationCompleted);
            }
            this.InvokeAsync("RECUPERARPREGUNTASR", new object[] {
                        Usuarioemail}, this.RECUPERARPREGUNTASROperationCompleted, userState);
        }
        
        private void OnRECUPERARPREGUNTASROperationCompleted(object arg) {
            if ((this.RECUPERARPREGUNTASRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RECUPERARPREGUNTASRCompleted(this, new RECUPERARPREGUNTASRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.RECUPERARVALUEPREGUNTASR", RequestElementName="PaquetesPopularesWS.RECUPERARVALUEPREGUNTASR", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.RECUPERARVALUEPREGUNTASRResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Tramarp")]
        public string RECUPERARVALUEPREGUNTASR(string Usuarioemail) {
            object[] results = this.Invoke("RECUPERARVALUEPREGUNTASR", new object[] {
                        Usuarioemail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RECUPERARVALUEPREGUNTASRAsync(string Usuarioemail) {
            this.RECUPERARVALUEPREGUNTASRAsync(Usuarioemail, null);
        }
        
        /// <remarks/>
        public void RECUPERARVALUEPREGUNTASRAsync(string Usuarioemail, object userState) {
            if ((this.RECUPERARVALUEPREGUNTASROperationCompleted == null)) {
                this.RECUPERARVALUEPREGUNTASROperationCompleted = new System.Threading.SendOrPostCallback(this.OnRECUPERARVALUEPREGUNTASROperationCompleted);
            }
            this.InvokeAsync("RECUPERARVALUEPREGUNTASR", new object[] {
                        Usuarioemail}, this.RECUPERARVALUEPREGUNTASROperationCompleted, userState);
        }
        
        private void OnRECUPERARVALUEPREGUNTASROperationCompleted(object arg) {
            if ((this.RECUPERARVALUEPREGUNTASRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RECUPERARVALUEPREGUNTASRCompleted(this, new RECUPERARVALUEPREGUNTASRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.ACTUALIZARPASSWORD", RequestElementName="PaquetesPopularesWS.ACTUALIZARPASSWORD", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.ACTUALIZARPASSWORDResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Valido")]
        public short ACTUALIZARPASSWORD(string Usuarioemail, string Usuariopassword) {
            object[] results = this.Invoke("ACTUALIZARPASSWORD", new object[] {
                        Usuarioemail,
                        Usuariopassword});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void ACTUALIZARPASSWORDAsync(string Usuarioemail, string Usuariopassword) {
            this.ACTUALIZARPASSWORDAsync(Usuarioemail, Usuariopassword, null);
        }
        
        /// <remarks/>
        public void ACTUALIZARPASSWORDAsync(string Usuarioemail, string Usuariopassword, object userState) {
            if ((this.ACTUALIZARPASSWORDOperationCompleted == null)) {
                this.ACTUALIZARPASSWORDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnACTUALIZARPASSWORDOperationCompleted);
            }
            this.InvokeAsync("ACTUALIZARPASSWORD", new object[] {
                        Usuarioemail,
                        Usuariopassword}, this.ACTUALIZARPASSWORDOperationCompleted, userState);
        }
        
        private void OnACTUALIZARPASSWORDOperationCompleted(object arg) {
            if ((this.ACTUALIZARPASSWORDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ACTUALIZARPASSWORDCompleted(this, new ACTUALIZARPASSWORDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.TEOFRECEMOS", RequestElementName="PaquetesPopularesWS.TEOFRECEMOS", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.TEOFRECEMOSResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paginacontenidohtml")]
        public string TEOFRECEMOS(string Tipopag) {
            object[] results = this.Invoke("TEOFRECEMOS", new object[] {
                        Tipopag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TEOFRECEMOSAsync(string Tipopag) {
            this.TEOFRECEMOSAsync(Tipopag, null);
        }
        
        /// <remarks/>
        public void TEOFRECEMOSAsync(string Tipopag, object userState) {
            if ((this.TEOFRECEMOSOperationCompleted == null)) {
                this.TEOFRECEMOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTEOFRECEMOSOperationCompleted);
            }
            this.InvokeAsync("TEOFRECEMOS", new object[] {
                        Tipopag}, this.TEOFRECEMOSOperationCompleted, userState);
        }
        
        private void OnTEOFRECEMOSOperationCompleted(object arg) {
            if ((this.TEOFRECEMOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TEOFRECEMOSCompleted(this, new TEOFRECEMOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.VERIFICARUSUARIOREDES", RequestElementName="PaquetesPopularesWS.VERIFICARUSUARIOREDES", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.VERIFICARUSUARIOREDESResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Valido")]
        public short VERIFICARUSUARIOREDES(string Usuarioemail) {
            object[] results = this.Invoke("VERIFICARUSUARIOREDES", new object[] {
                        Usuarioemail});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void VERIFICARUSUARIOREDESAsync(string Usuarioemail) {
            this.VERIFICARUSUARIOREDESAsync(Usuarioemail, null);
        }
        
        /// <remarks/>
        public void VERIFICARUSUARIOREDESAsync(string Usuarioemail, object userState) {
            if ((this.VERIFICARUSUARIOREDESOperationCompleted == null)) {
                this.VERIFICARUSUARIOREDESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVERIFICARUSUARIOREDESOperationCompleted);
            }
            this.InvokeAsync("VERIFICARUSUARIOREDES", new object[] {
                        Usuarioemail}, this.VERIFICARUSUARIOREDESOperationCompleted, userState);
        }
        
        private void OnVERIFICARUSUARIOREDESOperationCompleted(object arg) {
            if ((this.VERIFICARUSUARIOREDESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VERIFICARUSUARIOREDESCompleted(this, new VERIFICARUSUARIOREDESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.GETINFORMACIONADICIONAL", RequestElementName="PaquetesPopularesWS.GETINFORMACIONADICIONAL", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.GETINFORMACIONADICIONALResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Tramainformacionadicional")]
        public string GETINFORMACIONADICIONAL(string Usuarioemail) {
            object[] results = this.Invoke("GETINFORMACIONADICIONAL", new object[] {
                        Usuarioemail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETINFORMACIONADICIONALAsync(string Usuarioemail) {
            this.GETINFORMACIONADICIONALAsync(Usuarioemail, null);
        }
        
        /// <remarks/>
        public void GETINFORMACIONADICIONALAsync(string Usuarioemail, object userState) {
            if ((this.GETINFORMACIONADICIONALOperationCompleted == null)) {
                this.GETINFORMACIONADICIONALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETINFORMACIONADICIONALOperationCompleted);
            }
            this.InvokeAsync("GETINFORMACIONADICIONAL", new object[] {
                        Usuarioemail}, this.GETINFORMACIONADICIONALOperationCompleted, userState);
        }
        
        private void OnGETINFORMACIONADICIONALOperationCompleted(object arg) {
            if ((this.GETINFORMACIONADICIONALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETINFORMACIONADICIONALCompleted(this, new GETINFORMACIONADICIONALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.BUSQUEDAPAQUETES", RequestElementName="PaquetesPopularesWS.BUSQUEDAPAQUETES", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.BUSQUEDAPAQUETESResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Busquedahtml")]
        public string BUSQUEDAPAQUETES(short Tipo, double Valor) {
            object[] results = this.Invoke("BUSQUEDAPAQUETES", new object[] {
                        Tipo,
                        Valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BUSQUEDAPAQUETESAsync(short Tipo, double Valor) {
            this.BUSQUEDAPAQUETESAsync(Tipo, Valor, null);
        }
        
        /// <remarks/>
        public void BUSQUEDAPAQUETESAsync(short Tipo, double Valor, object userState) {
            if ((this.BUSQUEDAPAQUETESOperationCompleted == null)) {
                this.BUSQUEDAPAQUETESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBUSQUEDAPAQUETESOperationCompleted);
            }
            this.InvokeAsync("BUSQUEDAPAQUETES", new object[] {
                        Tipo,
                        Valor}, this.BUSQUEDAPAQUETESOperationCompleted, userState);
        }
        
        private void OnBUSQUEDAPAQUETESOperationCompleted(object arg) {
            if ((this.BUSQUEDAPAQUETESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BUSQUEDAPAQUETESCompleted(this, new BUSQUEDAPAQUETESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.SELECCIONARPAGINACONTENIDO", RequestElementName="PaquetesPopularesWS.SELECCIONARPAGINACONTENIDO", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.SELECCIONARPAGINACONTENIDOResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paginacontid")]
        public int SELECCIONARPAGINACONTENIDO(string Paginacontnom) {
            object[] results = this.Invoke("SELECCIONARPAGINACONTENIDO", new object[] {
                        Paginacontnom});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SELECCIONARPAGINACONTENIDOAsync(string Paginacontnom) {
            this.SELECCIONARPAGINACONTENIDOAsync(Paginacontnom, null);
        }
        
        /// <remarks/>
        public void SELECCIONARPAGINACONTENIDOAsync(string Paginacontnom, object userState) {
            if ((this.SELECCIONARPAGINACONTENIDOOperationCompleted == null)) {
                this.SELECCIONARPAGINACONTENIDOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSELECCIONARPAGINACONTENIDOOperationCompleted);
            }
            this.InvokeAsync("SELECCIONARPAGINACONTENIDO", new object[] {
                        Paginacontnom}, this.SELECCIONARPAGINACONTENIDOOperationCompleted, userState);
        }
        
        private void OnSELECCIONARPAGINACONTENIDOOperationCompleted(object arg) {
            if ((this.SELECCIONARPAGINACONTENIDOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SELECCIONARPAGINACONTENIDOCompleted(this, new SELECCIONARPAGINACONTENIDOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.OBTENERNOMBREAPELLIDO", RequestElementName="PaquetesPopularesWS.OBTENERNOMBREAPELLIDO", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.OBTENERNOMBREAPELLIDOResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Trama")]
        public string OBTENERNOMBREAPELLIDO(string Usuarioemail) {
            object[] results = this.Invoke("OBTENERNOMBREAPELLIDO", new object[] {
                        Usuarioemail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OBTENERNOMBREAPELLIDOAsync(string Usuarioemail) {
            this.OBTENERNOMBREAPELLIDOAsync(Usuarioemail, null);
        }
        
        /// <remarks/>
        public void OBTENERNOMBREAPELLIDOAsync(string Usuarioemail, object userState) {
            if ((this.OBTENERNOMBREAPELLIDOOperationCompleted == null)) {
                this.OBTENERNOMBREAPELLIDOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOBTENERNOMBREAPELLIDOOperationCompleted);
            }
            this.InvokeAsync("OBTENERNOMBREAPELLIDO", new object[] {
                        Usuarioemail}, this.OBTENERNOMBREAPELLIDOOperationCompleted, userState);
        }
        
        private void OnOBTENERNOMBREAPELLIDOOperationCompleted(object arg) {
            if ((this.OBTENERNOMBREAPELLIDOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OBTENERNOMBREAPELLIDOCompleted(this, new OBTENERNOMBREAPELLIDOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.PAGINACONTENIDO", RequestElementName="PaquetesPopularesWS.PAGINACONTENIDO", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.PAGINACONTENIDOResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paginacontenidohtml")]
        public string PAGINACONTENIDO(int Id) {
            object[] results = this.Invoke("PAGINACONTENIDO", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PAGINACONTENIDOAsync(int Id) {
            this.PAGINACONTENIDOAsync(Id, null);
        }
        
        /// <remarks/>
        public void PAGINACONTENIDOAsync(int Id, object userState) {
            if ((this.PAGINACONTENIDOOperationCompleted == null)) {
                this.PAGINACONTENIDOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPAGINACONTENIDOOperationCompleted);
            }
            this.InvokeAsync("PAGINACONTENIDO", new object[] {
                        Id}, this.PAGINACONTENIDOOperationCompleted, userState);
        }
        
        private void OnPAGINACONTENIDOOperationCompleted(object arg) {
            if ((this.PAGINACONTENIDOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PAGINACONTENIDOCompleted(this, new PAGINACONTENIDOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.PAQUETES", RequestElementName="PaquetesPopularesWS.PAQUETES", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.PAQUETESResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Popularpaquetehtml")]
        public string PAQUETES() {
            object[] results = this.Invoke("PAQUETES", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PAQUETESAsync() {
            this.PAQUETESAsync(null);
        }
        
        /// <remarks/>
        public void PAQUETESAsync(object userState) {
            if ((this.PAQUETESOperationCompleted == null)) {
                this.PAQUETESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPAQUETESOperationCompleted);
            }
            this.InvokeAsync("PAQUETES", new object[0], this.PAQUETESOperationCompleted, userState);
        }
        
        private void OnPAQUETESOperationCompleted(object arg) {
            if ((this.PAQUETESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PAQUETESCompleted(this, new PAQUETESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.BOLETINFOOTER", RequestElementName="PaquetesPopularesWS.BOLETINFOOTER", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.BOLETINFOOTERResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Boletinhtml")]
        public string BOLETINFOOTER() {
            object[] results = this.Invoke("BOLETINFOOTER", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BOLETINFOOTERAsync() {
            this.BOLETINFOOTERAsync(null);
        }
        
        /// <remarks/>
        public void BOLETINFOOTERAsync(object userState) {
            if ((this.BOLETINFOOTEROperationCompleted == null)) {
                this.BOLETINFOOTEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnBOLETINFOOTEROperationCompleted);
            }
            this.InvokeAsync("BOLETINFOOTER", new object[0], this.BOLETINFOOTEROperationCompleted, userState);
        }
        
        private void OnBOLETINFOOTEROperationCompleted(object arg) {
            if ((this.BOLETINFOOTERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BOLETINFOOTERCompleted(this, new BOLETINFOOTERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.DESTINOS", RequestElementName="PaquetesPopularesWS.DESTINOS", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.DESTINOSResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Destinopopularhtml")]
        public string DESTINOS() {
            object[] results = this.Invoke("DESTINOS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DESTINOSAsync() {
            this.DESTINOSAsync(null);
        }
        
        /// <remarks/>
        public void DESTINOSAsync(object userState) {
            if ((this.DESTINOSOperationCompleted == null)) {
                this.DESTINOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDESTINOSOperationCompleted);
            }
            this.InvokeAsync("DESTINOS", new object[0], this.DESTINOSOperationCompleted, userState);
        }
        
        private void OnDESTINOSOperationCompleted(object arg) {
            if ((this.DESTINOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DESTINOSCompleted(this, new DESTINOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.DESTINODETALLE", RequestElementName="PaquetesPopularesWS.DESTINODETALLE", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.DESTINODETALLEResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Destinodetailhtml")]
        public string DESTINODETALLE(int Id) {
            object[] results = this.Invoke("DESTINODETALLE", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DESTINODETALLEAsync(int Id) {
            this.DESTINODETALLEAsync(Id, null);
        }
        
        /// <remarks/>
        public void DESTINODETALLEAsync(int Id, object userState) {
            if ((this.DESTINODETALLEOperationCompleted == null)) {
                this.DESTINODETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDESTINODETALLEOperationCompleted);
            }
            this.InvokeAsync("DESTINODETALLE", new object[] {
                        Id}, this.DESTINODETALLEOperationCompleted, userState);
        }
        
        private void OnDESTINODETALLEOperationCompleted(object arg) {
            if ((this.DESTINODETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DESTINODETALLECompleted(this, new DESTINODETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.COTIZARPAQUETE", RequestElementName="PaquetesPopularesWS.COTIZARPAQUETE", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.COTIZARPAQUETEResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Destinodetailhtml")]
        public string COTIZARPAQUETE(int Id) {
            object[] results = this.Invoke("COTIZARPAQUETE", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void COTIZARPAQUETEAsync(int Id) {
            this.COTIZARPAQUETEAsync(Id, null);
        }
        
        /// <remarks/>
        public void COTIZARPAQUETEAsync(int Id, object userState) {
            if ((this.COTIZARPAQUETEOperationCompleted == null)) {
                this.COTIZARPAQUETEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCOTIZARPAQUETEOperationCompleted);
            }
            this.InvokeAsync("COTIZARPAQUETE", new object[] {
                        Id}, this.COTIZARPAQUETEOperationCompleted, userState);
        }
        
        private void OnCOTIZARPAQUETEOperationCompleted(object arg) {
            if ((this.COTIZARPAQUETECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.COTIZARPAQUETECompleted(this, new COTIZARPAQUETECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.COORDENADASPAQUETE", RequestElementName="PaquetesPopularesWS.COORDENADASPAQUETE", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.COORDENADASPAQUETEResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Paqueteubicacion")]
        public string COORDENADASPAQUETE(int Id) {
            object[] results = this.Invoke("COORDENADASPAQUETE", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void COORDENADASPAQUETEAsync(int Id) {
            this.COORDENADASPAQUETEAsync(Id, null);
        }
        
        /// <remarks/>
        public void COORDENADASPAQUETEAsync(int Id, object userState) {
            if ((this.COORDENADASPAQUETEOperationCompleted == null)) {
                this.COORDENADASPAQUETEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCOORDENADASPAQUETEOperationCompleted);
            }
            this.InvokeAsync("COORDENADASPAQUETE", new object[] {
                        Id}, this.COORDENADASPAQUETEOperationCompleted, userState);
        }
        
        private void OnCOORDENADASPAQUETEOperationCompleted(object arg) {
            if ((this.COORDENADASPAQUETECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.COORDENADASPAQUETECompleted(this, new COORDENADASPAQUETECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.CONTACTOALMACENAR", RequestElementName="PaquetesPopularesWS.CONTACTOALMACENAR", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.CONTACTOALMACENARResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("retval")]
        public string CONTACTOALMACENAR(string Nombre1, string Nombre2, string Correo, string Telefono, string Comentario) {
            object[] results = this.Invoke("CONTACTOALMACENAR", new object[] {
                        Nombre1,
                        Nombre2,
                        Correo,
                        Telefono,
                        Comentario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CONTACTOALMACENARAsync(string Nombre1, string Nombre2, string Correo, string Telefono, string Comentario) {
            this.CONTACTOALMACENARAsync(Nombre1, Nombre2, Correo, Telefono, Comentario, null);
        }
        
        /// <remarks/>
        public void CONTACTOALMACENARAsync(string Nombre1, string Nombre2, string Correo, string Telefono, string Comentario, object userState) {
            if ((this.CONTACTOALMACENAROperationCompleted == null)) {
                this.CONTACTOALMACENAROperationCompleted = new System.Threading.SendOrPostCallback(this.OnCONTACTOALMACENAROperationCompleted);
            }
            this.InvokeAsync("CONTACTOALMACENAR", new object[] {
                        Nombre1,
                        Nombre2,
                        Correo,
                        Telefono,
                        Comentario}, this.CONTACTOALMACENAROperationCompleted, userState);
        }
        
        private void OnCONTACTOALMACENAROperationCompleted(object arg) {
            if ((this.CONTACTOALMACENARCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CONTACTOALMACENARCompleted(this, new CONTACTOALMACENARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.CONTACTO", RequestElementName="PaquetesPopularesWS.CONTACTO", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.CONTACTOResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Contactohtml")]
        public string CONTACTO() {
            object[] results = this.Invoke("CONTACTO", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CONTACTOAsync() {
            this.CONTACTOAsync(null);
        }
        
        /// <remarks/>
        public void CONTACTOAsync(object userState) {
            if ((this.CONTACTOOperationCompleted == null)) {
                this.CONTACTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCONTACTOOperationCompleted);
            }
            this.InvokeAsync("CONTACTO", new object[0], this.CONTACTOOperationCompleted, userState);
        }
        
        private void OnCONTACTOOperationCompleted(object arg) {
            if ((this.CONTACTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CONTACTOCompleted(this, new CONTACTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.CATEGORIASBUSQUEDA", RequestElementName="PaquetesPopularesWS.CATEGORIASBUSQUEDA", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.CATEGORIASBUSQUEDAResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Catbusquedahtml")]
        public string CATEGORIASBUSQUEDA() {
            object[] results = this.Invoke("CATEGORIASBUSQUEDA", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CATEGORIASBUSQUEDAAsync() {
            this.CATEGORIASBUSQUEDAAsync(null);
        }
        
        /// <remarks/>
        public void CATEGORIASBUSQUEDAAsync(object userState) {
            if ((this.CATEGORIASBUSQUEDAOperationCompleted == null)) {
                this.CATEGORIASBUSQUEDAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCATEGORIASBUSQUEDAOperationCompleted);
            }
            this.InvokeAsync("CATEGORIASBUSQUEDA", new object[0], this.CATEGORIASBUSQUEDAOperationCompleted, userState);
        }
        
        private void OnCATEGORIASBUSQUEDAOperationCompleted(object arg) {
            if ((this.CATEGORIASBUSQUEDACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CATEGORIASBUSQUEDACompleted(this, new CATEGORIASBUSQUEDACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.REGISTROUSUARIO", RequestElementName="PaquetesPopularesWS.REGISTROUSUARIO", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.REGISTROUSUARIOResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Valido")]
        public short REGISTROUSUARIO(string Usuarionombre, string Usuarioapellidos, string Usuariopassword, string Usuarioemail, string Usuariotipologin) {
            object[] results = this.Invoke("REGISTROUSUARIO", new object[] {
                        Usuarionombre,
                        Usuarioapellidos,
                        Usuariopassword,
                        Usuarioemail,
                        Usuariotipologin});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void REGISTROUSUARIOAsync(string Usuarionombre, string Usuarioapellidos, string Usuariopassword, string Usuarioemail, string Usuariotipologin) {
            this.REGISTROUSUARIOAsync(Usuarionombre, Usuarioapellidos, Usuariopassword, Usuarioemail, Usuariotipologin, null);
        }
        
        /// <remarks/>
        public void REGISTROUSUARIOAsync(string Usuarionombre, string Usuarioapellidos, string Usuariopassword, string Usuarioemail, string Usuariotipologin, object userState) {
            if ((this.REGISTROUSUARIOOperationCompleted == null)) {
                this.REGISTROUSUARIOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnREGISTROUSUARIOOperationCompleted);
            }
            this.InvokeAsync("REGISTROUSUARIO", new object[] {
                        Usuarionombre,
                        Usuarioapellidos,
                        Usuariopassword,
                        Usuarioemail,
                        Usuariotipologin}, this.REGISTROUSUARIOOperationCompleted, userState);
        }
        
        private void OnREGISTROUSUARIOOperationCompleted(object arg) {
            if ((this.REGISTROUSUARIOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.REGISTROUSUARIOCompleted(this, new REGISTROUSUARIOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.INICIARSESION", RequestElementName="PaquetesPopularesWS.INICIARSESION", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.INICIARSESIONResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Trama")]
        public string INICIARSESION(string Usuarioemail, string Usuariopassword) {
            object[] results = this.Invoke("INICIARSESION", new object[] {
                        Usuarioemail,
                        Usuariopassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INICIARSESIONAsync(string Usuarioemail, string Usuariopassword) {
            this.INICIARSESIONAsync(Usuarioemail, Usuariopassword, null);
        }
        
        /// <remarks/>
        public void INICIARSESIONAsync(string Usuarioemail, string Usuariopassword, object userState) {
            if ((this.INICIARSESIONOperationCompleted == null)) {
                this.INICIARSESIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINICIARSESIONOperationCompleted);
            }
            this.InvokeAsync("INICIARSESION", new object[] {
                        Usuarioemail,
                        Usuariopassword}, this.INICIARSESIONOperationCompleted, userState);
        }
        
        private void OnINICIARSESIONOperationCompleted(object arg) {
            if ((this.INICIARSESIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INICIARSESIONCompleted(this, new INICIARSESIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.INFORMACIONADICIONAL", RequestElementName="PaquetesPopularesWS.INFORMACIONADICIONAL", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.INFORMACIONADICIONALResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Valido")]
        public short INFORMACIONADICIONAL(string Usuarionombre, string Usuarioapellidos, string Usuarioemail, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Usuariofechanacimiento, string Usuariociudadresidencia, string Usuariotelefono, string Usuariocelular, string Usuariopasaporte, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Usuariofechavenc, string Usuariovisa, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Usuariovisafechavenc, string Usuarionacionalidad) {
            object[] results = this.Invoke("INFORMACIONADICIONAL", new object[] {
                        Usuarionombre,
                        Usuarioapellidos,
                        Usuarioemail,
                        Usuariofechanacimiento,
                        Usuariociudadresidencia,
                        Usuariotelefono,
                        Usuariocelular,
                        Usuariopasaporte,
                        Usuariofechavenc,
                        Usuariovisa,
                        Usuariovisafechavenc,
                        Usuarionacionalidad});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void INFORMACIONADICIONALAsync(string Usuarionombre, string Usuarioapellidos, string Usuarioemail, System.DateTime Usuariofechanacimiento, string Usuariociudadresidencia, string Usuariotelefono, string Usuariocelular, string Usuariopasaporte, System.DateTime Usuariofechavenc, string Usuariovisa, System.DateTime Usuariovisafechavenc, string Usuarionacionalidad) {
            this.INFORMACIONADICIONALAsync(Usuarionombre, Usuarioapellidos, Usuarioemail, Usuariofechanacimiento, Usuariociudadresidencia, Usuariotelefono, Usuariocelular, Usuariopasaporte, Usuariofechavenc, Usuariovisa, Usuariovisafechavenc, Usuarionacionalidad, null);
        }
        
        /// <remarks/>
        public void INFORMACIONADICIONALAsync(string Usuarionombre, string Usuarioapellidos, string Usuarioemail, System.DateTime Usuariofechanacimiento, string Usuariociudadresidencia, string Usuariotelefono, string Usuariocelular, string Usuariopasaporte, System.DateTime Usuariofechavenc, string Usuariovisa, System.DateTime Usuariovisafechavenc, string Usuarionacionalidad, object userState) {
            if ((this.INFORMACIONADICIONALOperationCompleted == null)) {
                this.INFORMACIONADICIONALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINFORMACIONADICIONALOperationCompleted);
            }
            this.InvokeAsync("INFORMACIONADICIONAL", new object[] {
                        Usuarionombre,
                        Usuarioapellidos,
                        Usuarioemail,
                        Usuariofechanacimiento,
                        Usuariociudadresidencia,
                        Usuariotelefono,
                        Usuariocelular,
                        Usuariopasaporte,
                        Usuariofechavenc,
                        Usuariovisa,
                        Usuariovisafechavenc,
                        Usuarionacionalidad}, this.INFORMACIONADICIONALOperationCompleted, userState);
        }
        
        private void OnINFORMACIONADICIONALOperationCompleted(object arg) {
            if ((this.INFORMACIONADICIONALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INFORMACIONADICIONALCompleted(this, new INFORMACIONADICIONALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TravelAdminaction/APAQUETESPOPULARESWS.RECOMENDADOS", RequestElementName="PaquetesPopularesWS.RECOMENDADOS", RequestNamespace="TravelAdmin", ResponseElementName="PaquetesPopularesWS.RECOMENDADOSResponse", ResponseNamespace="TravelAdmin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Recomendadohtml")]
        public string RECOMENDADOS() {
            object[] results = this.Invoke("RECOMENDADOS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RECOMENDADOSAsync() {
            this.RECOMENDADOSAsync(null);
        }
        
        /// <remarks/>
        public void RECOMENDADOSAsync(object userState) {
            if ((this.RECOMENDADOSOperationCompleted == null)) {
                this.RECOMENDADOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRECOMENDADOSOperationCompleted);
            }
            this.InvokeAsync("RECOMENDADOS", new object[0], this.RECOMENDADOSOperationCompleted, userState);
        }
        
        private void OnRECOMENDADOSOperationCompleted(object arg) {
            if ((this.RECOMENDADOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RECOMENDADOSCompleted(this, new RECOMENDADOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OBTENERPREGUNTASCompletedEventHandler(object sender, OBTENERPREGUNTASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OBTENERPREGUNTASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OBTENERPREGUNTASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SLIDERCompletedEventHandler(object sender, SLIDERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SLIDERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SLIDERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CATALOGOSCompletedEventHandler(object sender, CATALOGOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CATALOGOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CATALOGOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HEADERPUBLICIDADCompletedEventHandler(object sender, HEADERPUBLICIDADCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HEADERPUBLICIDADCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HEADERPUBLICIDADCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HEADERTELEFONOCompletedEventHandler(object sender, HEADERTELEFONOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HEADERTELEFONOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HEADERTELEFONOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GUARDARPREGUNTASCompletedEventHandler(object sender, GUARDARPREGUNTASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GUARDARPREGUNTASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GUARDARPREGUNTASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RECUPERARPREGUNTASRCompletedEventHandler(object sender, RECUPERARPREGUNTASRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RECUPERARPREGUNTASRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RECUPERARPREGUNTASRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RECUPERARVALUEPREGUNTASRCompletedEventHandler(object sender, RECUPERARVALUEPREGUNTASRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RECUPERARVALUEPREGUNTASRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RECUPERARVALUEPREGUNTASRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ACTUALIZARPASSWORDCompletedEventHandler(object sender, ACTUALIZARPASSWORDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ACTUALIZARPASSWORDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ACTUALIZARPASSWORDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TEOFRECEMOSCompletedEventHandler(object sender, TEOFRECEMOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TEOFRECEMOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TEOFRECEMOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void VERIFICARUSUARIOREDESCompletedEventHandler(object sender, VERIFICARUSUARIOREDESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VERIFICARUSUARIOREDESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VERIFICARUSUARIOREDESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GETINFORMACIONADICIONALCompletedEventHandler(object sender, GETINFORMACIONADICIONALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETINFORMACIONADICIONALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETINFORMACIONADICIONALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BUSQUEDAPAQUETESCompletedEventHandler(object sender, BUSQUEDAPAQUETESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BUSQUEDAPAQUETESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BUSQUEDAPAQUETESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SELECCIONARPAGINACONTENIDOCompletedEventHandler(object sender, SELECCIONARPAGINACONTENIDOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SELECCIONARPAGINACONTENIDOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SELECCIONARPAGINACONTENIDOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OBTENERNOMBREAPELLIDOCompletedEventHandler(object sender, OBTENERNOMBREAPELLIDOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OBTENERNOMBREAPELLIDOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OBTENERNOMBREAPELLIDOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PAGINACONTENIDOCompletedEventHandler(object sender, PAGINACONTENIDOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PAGINACONTENIDOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PAGINACONTENIDOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PAQUETESCompletedEventHandler(object sender, PAQUETESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PAQUETESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PAQUETESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BOLETINFOOTERCompletedEventHandler(object sender, BOLETINFOOTERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BOLETINFOOTERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BOLETINFOOTERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DESTINOSCompletedEventHandler(object sender, DESTINOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DESTINOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DESTINOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DESTINODETALLECompletedEventHandler(object sender, DESTINODETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DESTINODETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DESTINODETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void COTIZARPAQUETECompletedEventHandler(object sender, COTIZARPAQUETECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class COTIZARPAQUETECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal COTIZARPAQUETECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void COORDENADASPAQUETECompletedEventHandler(object sender, COORDENADASPAQUETECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class COORDENADASPAQUETECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal COORDENADASPAQUETECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CONTACTOALMACENARCompletedEventHandler(object sender, CONTACTOALMACENARCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CONTACTOALMACENARCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CONTACTOALMACENARCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CONTACTOCompletedEventHandler(object sender, CONTACTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CONTACTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CONTACTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CATEGORIASBUSQUEDACompletedEventHandler(object sender, CATEGORIASBUSQUEDACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CATEGORIASBUSQUEDACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CATEGORIASBUSQUEDACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void REGISTROUSUARIOCompletedEventHandler(object sender, REGISTROUSUARIOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class REGISTROUSUARIOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal REGISTROUSUARIOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void INICIARSESIONCompletedEventHandler(object sender, INICIARSESIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INICIARSESIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INICIARSESIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void INFORMACIONADICIONALCompletedEventHandler(object sender, INFORMACIONADICIONALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INFORMACIONADICIONALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INFORMACIONADICIONALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RECOMENDADOSCompletedEventHandler(object sender, RECOMENDADOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RECOMENDADOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RECOMENDADOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591